### PR TITLE
Add JUnit tests for TimeTableCommand and TimeTableCommandParser

### PR DESCRIPTION
**Pull request by Aseanseen**

### CODE REVIEW

**Comment by SimJunYou** [comment]
What's the bug?

**Comment by Aseanseen** [comment]
> What's the bug?

Used to be a bug with the JUnit tests, but it has been fixed.

**Comment by Aseanseen** [comment]
Accidentally closed this PR, reopening

**Review by SimJunYou — APPROVED** [review]
Looks okay

**Pull request merged**
