### PR TITLE
Added main sequence diagram parts

### PR DESCRIPTION
**Pull request by SimJunYou**
Forgot to add the 3 main sequence diagram parts

### CODE REVIEW

**Review by Aseanseen — APPROVED** [review]
Good to merge

**Review by weisiong24 — COMMENTED** [review]
dg


The above top class design is too messy with arrow and it might confused the reader. A  proper arrow head would improve readibility to the readers about your application.

The circle portion of the diagram I have marked may be hard for user to get a better picture of the flow of your design.
Perharps, use straight lines or adjust the different box accordingly so that user can follow through the flow of the design

**Review by weisiong24 — COMMENTED** [review]
image
The arrow coverges too much in the circled portion and thus it is making the class diagram more complicated than it should have been.  Maybe try to simplify the diagram by breaking it into portions or structure the arrows in a way that it is straight and pointing the class table more clearly.

**Review by weisiong24 — COMMENTED** [review]
dg


The above top class design is too messy with arrow and it might confused the reader. A  proper arrow head would improve readibility to the readers about your application.

The circle portion of the diagram I have marked may be hard for user to get a better picture of the flow of your design.
Perharps, use straight lines or adjust the different box accordingly so that user can follow through the flow of the design

**Review by weisiong24 — COMMENTED** [review]
image
Inconsistent arrow used (dotted and solid arrow) and the arrow head in the circled area is over the box which should have only been hit the box only.
Lack of system architecture diagram to show the overall design of the program. (only uml and sequence diagram is available).

For this diagram, it is hard to interpret if it is a uml class diagram as the boxes used are wrong and format of the diagram is not consistent with the format of a  standard uml class diagram.

**Review by weisiong24 — COMMENTED** [review]
dg3

The circle highlighted portion for the sequence design is very small and hard to see the different components/operations. It would improve the visusal better if more spaces are given to the main ravi box for the sequence diagram.

**Pull request merged**
