### PR TITLE
Added Cap and Grade Seq diagrams

### PR DESCRIPTION
**Pull request by tobiasceg**

### CODE REVIEW

**Review by Aseanseen — CHANGES_REQUESTED** [review]
Please add the diagrams into the DG and explain with reference to the diagrams

**Comment by tobiasceg** [comment]
> Please add the diagrams into the DG and explain with reference to the diagrams

RESOLVED ALREADY THANK YOU

**Comment by tobiasceg** [comment]
accidentally closed PR

**Review by Aseanseen — APPROVED** [review]
Looks good to merge

**Pull request merged**
